### ISSUE TITLE
[0.8b] "enter" is executed after the second typed character

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/vpcs#10]
the cli automatically execute "enter" after the second character typed:

![selection_008_29_09](https://user-images.githubusercontent.com/1716020/31022638-ab382f16-a539-11e7-95c5-a34d9c9ba8c3.jpg)

![selection_009_29_09](https://user-images.githubusercontent.com/1716020/31022614-983e5c78-a539-11e7-9276-366ef45be5da.jpg)

What is the last stable version?

**Comment by q2dg** [comment]
I have EXACTLY the same problem

**Comment by q2dg** [comment]
I've solved this issue and #13 following these intructions (VPCS section): http://binarynature.blogspot.com.es/2015/11/install-configure-gns3-arch-linux.html

**Comment by rifkiaz** [comment]
i got same problem.

**Comment by rifkiaz** [comment]
> I've solved this issue and #13 following these intructions (VPCS section): http://binarynature.blogspot.com.es/2015/11/install-configure-gns3-arch-linux.html

solved with this solution. 
Thanks!

**Comment by grossmj** [comment]
Fixed by https://github.com/GNS3/vpcs/issues/13
