### ISSUE TITLE
VPCS does not save default name

### ISSUE THREAD

**Issue by Raizo62** [GNS3/vpcs#11]
Hi

I use vpcs 0.6.2

I put on GNS3 a VPCS device : his default name is "VPCS-1"
I start it
His name is : VPCS-1
On OS : cat projects/untitled/project-files/vpcs/794eb714-30c7-41eb-b711-b4f33c91ee21/startup.vpc
`set pcname VPCS-1`

I save his config : save
On OS : cat projects/untitled/project-files/vpcs/794eb714-30c7-41eb-b711-b4f33c91ee21/startup.vpc
The file is empty

If i restart this device, his name is "VPCS"

**Comment by grossmj** [comment]
Fixed by https://github.com/GNS3/vpcs/pull/12
