### ISSUE TITLE
An improper locking bug(e.g., deadlock) on the lock LIST_LOCK; 

### ISSUE THREAD

**Issue by ryancaicse** [GNS3/vpcs#35]
Hi, developers, thank you for your checking. It seems the lock `LIST_LOCK;`  is not released correctly when `hoff == 0 `in the function `ipreass6`?

https://github.com/GNS3/vpcs/blob/fa58d6a1e6b23685ef5ab9d84fdb1d85df883250/src/frag6.c#L191-L220

Best,

**Comment by grossmj** [comment]
Thanks, we going to check it out.
