### ISSUE TITLE
VPCS creates invalid ARP packet

### ISSUE THREAD

**Issue by ehlers** [GNS3/vpcs#9]
Tested both with vpcs 0.6.1 and 0.8c

https://www.gns3.com/qa/gns3-2-0-bad-checksum-should-be-

The ARP packets from VPCS are invalid, they are shown in wireshark as packets with invalid FCS. Dynamips router (tested with cisco 3725) ignores that and respond normally. But some router (e.g. NX-OSv and vSRX) ignore those invalid arp packets. Then pings from VPCS to the router won't work.

I'm not sure, that the issue is really a bad FCS. As far as I know the packets in the UDP tunnel don't include a FCS.

**Comment by noplay** [comment]
Could explain the troubles of VPCS when directly connected to cloud node on
Windows.

**Comment by ehlers** [comment]
My fix, now wireshark is happy:
```
diff --git a/src/ip.h b/src/ip.h
index 0225d99..bb8e0df 100644
--- a/src/ip.h
+++ b/src/ip.h
@@ -239,7 +239,7 @@ typedef struct tcpiphdr tcpiphdr;
 #define TCPOLEN_TIMESTAMP       10

 #define PKT_MAXSIZE 1520
-#define ARP_PSIZE 64
+#define ARP_PSIZE 60
 #define ICMP_PSIZE 128
 #define UDP_PSIZE 128
```

The ARP packet is smaller than the minimum ethernet size (64), so it's padded to 60 bytes plus the FCS results in a 64 bytes ethernet frame. But VPCS originally created a 64 byte frame, what was interpreted as 60 byte data + 4 byte FCS, what was not intended.

**Comment by ehlers** [comment]
After further analysis I'm not sure, how important this issue is. Wireshark isn't happy about this ARP frame, but I couldn't reproduce having an issue with vSRX. So maybe I had another issue while testing the first time. And Andrew had no issue using this ARP towards NX-OSv (see the forum discussion).

So currently it looks more like an annoyance than an import issue.

**Comment by grossmj** [comment]
We don't really want to become the official maintainer for VPCS. We are looking at creating our own Python based implementation of VPCS.

What we can do for now if forward your patch to the creator of VPCS but I don't know think he still works on the project :(

**Comment by ehlers** [comment]
Won't be fixed.
